name: ai_semantic_mobile_app
description: A Flutter mobile application integrating advanced AI capabilities and utilizing vector databases for efficient semantic searches.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2

  flutter_markdown: ^0.6.18

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true